#!/bin/bash

# Configuring lighttpd
/usr/sbin/lighttpd-enable-mod fastcgi
/usr/sbin/lighttpd-enable-mod fastcgi-php
/etc/init.d/lighttpd restart

# Setting rights
/bin/chown -R www-data:www-data /www
/bin/chown root:root /etc/cron.d/wifi_rover
/bin/chmod 0600 /etc/cron.d/wifi_rover
/bin/chown -R root:root /etc/sudoers.d
/bin/chmod 0440 /etc/sudoers.d/wifi_rover
#/bin/chmod 0755 /etc/watchdog.d/*

