#!/bin/bash

# setup cron
/bin/chown root:root /etc/cron.d/wifi_rover
/bin/chmod 0600 /etc/cron.d/wifi_rover

# setup sudo
/bin/chown -R root:root /etc/sudoers.d
/bin/chmod 0440 /etc/sudoers.d/wifi_rover

# setup watchdog
#/bin/chmod 0755 /etc/watchdog.d/*

# Setup web site
/bin/chown -R www-data:www-data /www
/usr/sbin/lighttpd-enable-mod fastcgi
/usr/sbin/lighttpd-enable-mod fastcgi-php
/etc/init.d/lighttpd restart

